### ISSUE TITLE
amqp-client.conn must not be private for shutdown to work

### ISSUE THREAD

**Issue by tobias-neubert** [ttab/amqp-as-promised#3]
I am trying to use the shutdown function to exit gracefully but get the following exception:

    TypeError: Cannot read property 'then' of undefined
    at QueueWrapper.module.exports.QueueWrapper.unbind (/Users/tobias.neubert/dev/projects/bookandsmile/bas-router/node_modules/amqp-as-promised/lib/queue-wrapper.js:64:22)
    at QueueWrapper.unbind (/Users/tobias.neubert/dev/projects/bookandsmile/bas-router/node_modules/amqp-as-promised/lib/queue-wrapper.js:4:61)
    at /Users/tobias.neubert/dev/projects/bookandsmile/bas-router/node_modules/amqp-as-promised/lib/amqp-client.js:184:18

To me it looks as if the queue-wrapper needs access to the amqp-client conn property. So I added the conn property to the exported object in amqp-client.js. But that results in another exception.

Here is how I am trying to get things done: I am thankful for any help,
Tobias

    function start() {
        // Register the exit hooks
        process.on('SIGTERM', exit);
        process.on('SIGINT', exit);

        return establishRegisterProviderQueue().then(function () {
            return establishRouterQueue();
        });
    };

    function exit() {
        logger.info('Exiting');
        amqpc.shutdown().then(function () {
            logger.info('Closed AMQP connection gracefully.');
            process.exit(0);
        }).catch(function (error) {
            logger.warn('Could not close AMQP connection gracefully. Will exit anyway: %s', error.stack);
            process.exit(10);
        });
    }

    function establishRegisterProviderQueue() {
        logger.info('Establishing provider registration');
        return Q.all([
            amqpc.exchange(REGISTER_PROVIDER_EXCHANGE_NAME, {
                type: 'fanout',
                passive: false
            }),
            amqpc.queue(REGISTER_PROVIDER_QUEUE_NAME, {passive: false})
        ]).spread(function (exchange, queue) {
            return amqpc.bind(exchange, queue, REGISTER_PROVIDER_ROUTING_KEY, registerProvider);
        });
    };

**Comment by fred-o** [comment]
Hi! As far as I can tell, the queue-wrapper object already should hold a reference to `amqpc.conn`, and it doesn't look like it is ever deleted. Does the queue work correctly for you up until shutdown, or could it be some kind of trouble with the initialization?
